name: currency_converter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  dependencies:
  auto_size_text_pk: ^3.0.0
  flutter_colorpicker: ^1.0.3
  math_expressions: ^2.2.0
  shared_preferences:
  dio: ^4.0.0
  smooth_star_rating: ^1.1.1
  rating_bar: ^0.2.0
  url_launcher:
  easy_localization:
  currency_text_input_formatter: ^2.1.3
  share:
  auto_size_text_field: ^1.0.1
  sqflite: ^2.0.1
  path_provider:
  path: ^1.8.0
  flutter_hsvcolor_picker:
  fluttertoast:
  flutter_widget_from_html_core:
  basic_utils:
  flutter_reorderable_list: ^1.2.0
  syncfusion_flutter_sliders:
  intl:
  flutter_svg: any
  flex_color_picker:
  google_mobile_ads:
  native_admob_flutter: any
  provider: any
  flutter_advertising_id: any 
  advertising_id: ^2.1.1
  get: any
  bot_toast: ^4.0.1
  flutter_inapp_purchase: 5.0.0
  appsflyer_sdk:
  device_info_plus:
  uuid:

  #For App widget
  home_widget:
  workmanager:

  flutter_echarts:
  syncfusion_flutter_charts:
  syncfusion_flutter_core:

dev_dependencies:

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/codes-map.json
    - assets/currency-symbols.json
    - assets/fonts/material_icons.ttf
    - assets/fonts/roboto_medium.ttf
    - assets/images/@1x/check.png
    - assets/images/@1x/cross.png
    - assets/images/@1x/currency.png
    - assets/images/@1x/right-left.png
    - assets/images/@1x/tab-ic1.png
    - assets/images/@1x/tab-ic1.svg
    - assets/images/@1x/tab-ic2.png
    - assets/images/@1x/tab-ic3.png
    - assets/images/@1x/tab-ic4.png
    - assets/images/@1x/tab-ic5.png
    - assets/images/@1x/tab-ic6.png
    - assets/images/@1x/tab1-ic5.png
    - assets/images/@1x/tooltip.png
    - assets/images/@1x/up-down.png
    - assets/images/@2x/check.png
    - assets/images/@2x/cross.png
    - assets/images/@2x/currency.png
    - assets/images/@2x/right-left.png
    - assets/images/@2x/tab-ic1.png
    - assets/images/@2x/tab-ic2.png
    - assets/images/@2x/tab-ic3.png
    - assets/images/@2x/tab-ic4.png
    - assets/images/@2x/tab-ic5.png
    - assets/images/@2x/tab-ic6.png
    - assets/images/@2x/tooltip.png
    - assets/images/@2x/up-down.png
    - assets/images/@3x/check.png
    - assets/images/@3x/cross.png
    - assets/images/@3x/currency.png
    - assets/images/@3x/right-left.png
    - assets/images/@3x/tab-ic1.png
    - assets/images/@3x/tab-ic2.png
    - assets/images/@3x/tab-ic3.png
    - assets/images/@3x/tab-ic4.png
    - assets/images/@3x/tab-ic5.png
    - assets/images/@3x/tab-ic6.png
    - assets/images/@3x/tooltip.png
    - assets/images/@3x/up-down.png
    - assets/images/about-dark.svg
    - assets/images/about-light.svg
    - assets/images/add.svg
    - assets/images/arrow-left.svg
    - assets/images/arrow-top.svg
    - assets/images/arrows-vertical.svg
    - assets/images/bar-chart.png
    - assets/images/bin.svg
    - assets/images/check-blank.svg
    - assets/images/check-round.svg
    - assets/images/close-red.svg
    - assets/images/close.svg
    - assets/images/currency-converter-dark.svg
    - assets/images/currency-converter-light.svg
    - assets/images/currency1.png
    - assets/images/feedback-illustration.svg
    - assets/images/ic_chevron_left_24px.svg
    - assets/images/ic_search_24px.svg
    - assets/images/logo.svg
    - assets/images/monetary-dark.svg
    - assets/images/monetary-light.svg
    - assets/images/multi-currency-dark.svg
    - assets/images/multi-currency-light.svg
    - assets/images/Path 436.svg
    - assets/images/plus-icon.svg
    - assets/images/plus.svg
    - assets/images/rate-dark.svg
    - assets/images/rate-light.svg
    - assets/images/right.svg
    - assets/images/settings-dark.svg
    - assets/images/settings-light.svg
    - assets/images/star-rate-blank.svg
    - assets/images/star-rate.svg
    - assets/images/star_24px.svg
    - assets/images/star_border_24px.svg
    - assets/images/widget-large1.svg
    - assets/images/widget-large2.svg
    - assets/images/widget-new.svg
    - assets/images/widget-new1.svg
    - assets/images/widget-new2.svg
    - assets/images/widget-new3.svg
    - assets/language/ar.json
    - assets/language/bg.json
    - assets/language/bn.json
    - assets/language/bs.json
    - assets/language/ca.json
    - assets/language/cs.json
    - assets/language/da.json
    - assets/language/de.json
    - assets/language/el.json
    - assets/language/en.json
    - assets/language/es.json
    - assets/language/et.json
    - assets/language/fi.json
    - assets/language/fil.json
    - assets/language/fr.json
    - assets/language/gu.json
    - assets/language/he.json
    - assets/language/hi.json
    - assets/language/hr-ba.json
    - assets/language/hr.json
    - assets/language/hu.json
    - assets/language/hy.json
    - assets/language/id.json
    - assets/language/it.json
    - assets/language/ja.json
    - assets/language/ka.json
    - assets/language/lt.json
    - assets/language/lv.json
    - assets/language/mr.json
    - assets/language/ms.json
    - assets/language/ne.json
    - assets/language/nl.json
    - assets/language/no.json
    - assets/language/pl.json
    - assets/language/pt.json
    - assets/language/ro.json
    - assets/language/ru.json
    - assets/language/sk.json
    - assets/language/sl.json
    - assets/language/sr.json
    - assets/language/sv.json
    - assets/language/ta.json
    - assets/language/te.json
    - assets/language/tr.json
    - assets/language/uk.json
    - assets/language/vi.json
    - assets/language/zh.json
    - assets/language_final/ar.json
    - assets/language_final/bg.json
    - assets/language_final/bn.json
    - assets/language_final/bs.json
    - assets/language_final/ca.json
    - assets/language_final/cs.json
    - assets/language_final/da.json
    - assets/language_final/de.json
    - assets/language_final/el.json
    - assets/language_final/en.json
    - assets/language_final/et.json
    - assets/language_final/fi.json
    - assets/language_final/fil.json
    - assets/language_final/fr.json
    - assets/language_final/gu.json
    - assets/language_final/hi.json
    - assets/language_final/hr.json
    - assets/language_final/hu.json
    - assets/language_final/hy.json
    - assets/language_final/id.json
    - assets/language_final/it.json
    - assets/language_final/iw.json
    - assets/language_final/ja.json
    - assets/language_final/ka.json
    - assets/language_final/lv.json
    - assets/language_final/mr.json
    - assets/language_final/ms.json
    - assets/language_final/ne.json
    - assets/language_final/nl.json
    - assets/language_final/no.json
    - assets/language_final/pl.json
    - assets/language_final/pt.json
    - assets/language_final/ro.json
    - assets/language_final/ru.json
    - assets/language_final/sk.json
    - assets/language_final/sl.json
    - assets/language_final/sr.json
    - assets/language_final/sv.json
    - assets/language_final/ta.json
    - assets/language_final/te.json
    - assets/language_final/tr.json
    - assets/language_final/uk.json
    - assets/language_final/vi.json
    - assets/language_final/zh.json
    - assets/pngCountryImages/AED.png
    - assets/pngCountryImages/AFN.png
    - assets/pngCountryImages/ALL.png
    - assets/pngCountryImages/AM.png
    - assets/pngCountryImages/AMD.png
    - assets/pngCountryImages/ANG.png
    - assets/pngCountryImages/AOA.png
    - assets/pngCountryImages/AR.png
    - assets/pngCountryImages/ARS.png
    - assets/pngCountryImages/ARS3.png
    - assets/pngCountryImages/AUD.png
    - assets/pngCountryImages/AWG.png
    - assets/pngCountryImages/AZN.png
    - assets/pngCountryImages/BAM.png
    - assets/pngCountryImages/BBD.png
    - assets/pngCountryImages/BDT.png
    - assets/pngCountryImages/BGN.png
    - assets/pngCountryImages/BHD.png
    - assets/pngCountryImages/BIF.png
    - assets/pngCountryImages/BMD.png
    - assets/pngCountryImages/BND.png
    - assets/pngCountryImages/BOB.png
    - assets/pngCountryImages/BRL.png
    - assets/pngCountryImages/BSD.png
    - assets/pngCountryImages/BTC.png
    - assets/pngCountryImages/BTN.png
    - assets/pngCountryImages/BWP.png
    - assets/pngCountryImages/BYN.png
    - assets/pngCountryImages/BZD.png
    - assets/pngCountryImages/CAD.png
    - assets/pngCountryImages/CDF.png
    - assets/pngCountryImages/CHF.png
    - assets/pngCountryImages/CLF.png
    - assets/pngCountryImages/CLP.png
    - assets/pngCountryImages/CNH.png
    - assets/pngCountryImages/CNY.png
    - assets/pngCountryImages/COP.png
    - assets/pngCountryImages/CRC.png
    - assets/pngCountryImages/CUC.png
    - assets/pngCountryImages/CUP.png
    - assets/pngCountryImages/CVE.png
    - assets/pngCountryImages/CZK.png
    - assets/pngCountryImages/DJF.png
    - assets/pngCountryImages/DKK.png
    - assets/pngCountryImages/DOP.png
    - assets/pngCountryImages/DZD.png
    - assets/pngCountryImages/EGP.png
    - assets/pngCountryImages/ERN.png
    - assets/pngCountryImages/ETB.png
    - assets/pngCountryImages/EUR.png
    - assets/pngCountryImages/FJD.png
    - assets/pngCountryImages/FKP.png
    - assets/pngCountryImages/FKP1.png
    - assets/pngCountryImages/GBP.png
    - assets/pngCountryImages/GEL.png
    - assets/pngCountryImages/GGP.png
    - assets/pngCountryImages/GHS.png
    - assets/pngCountryImages/GIP.png
    - assets/pngCountryImages/GMD.png
    - assets/pngCountryImages/GNF.png
    - assets/pngCountryImages/GTQ.png
    - assets/pngCountryImages/GYD.png
    - assets/pngCountryImages/HKD.png
    - assets/pngCountryImages/HNL.png
    - assets/pngCountryImages/HRK.png
    - assets/pngCountryImages/HTG.png
    - assets/pngCountryImages/HUF.png
    - assets/pngCountryImages/ic_bt.png
    - assets/pngCountryImages/IDR.png
    - assets/pngCountryImages/ILS.png
    - assets/pngCountryImages/IMP.png
    - assets/pngCountryImages/INR.png
    - assets/pngCountryImages/IQD.png
    - assets/pngCountryImages/IRR.png
    - assets/pngCountryImages/ISK.png
    - assets/pngCountryImages/JEP.png
    - assets/pngCountryImages/JMD.png
    - assets/pngCountryImages/JOD.png
    - assets/pngCountryImages/JPY.png
    - assets/pngCountryImages/KES.png
    - assets/pngCountryImages/KGS.png
    - assets/pngCountryImages/KHR.png
    - assets/pngCountryImages/KMF.png
    - assets/pngCountryImages/KPW.png
    - assets/pngCountryImages/KRW.png
    - assets/pngCountryImages/KWD.png
    - assets/pngCountryImages/KYD.png
    - assets/pngCountryImages/KZT.png
    - assets/pngCountryImages/LAK.png
    - assets/pngCountryImages/LBP.png
    - assets/pngCountryImages/LKR.png
    - assets/pngCountryImages/LRD.png
    - assets/pngCountryImages/LSL.png
    - assets/pngCountryImages/LYD.png
    - assets/pngCountryImages/MAD.png
    - assets/pngCountryImages/MDL.png
    - assets/pngCountryImages/MGA.png
    - assets/pngCountryImages/MKD.png
    - assets/pngCountryImages/MMK.png
    - assets/pngCountryImages/MNT.png
    - assets/pngCountryImages/MOP.png
    - assets/pngCountryImages/MRO.png
    - assets/pngCountryImages/MRU.png
    - assets/pngCountryImages/MUR.png
    - assets/pngCountryImages/MVR.png
    - assets/pngCountryImages/MWK.png
    - assets/pngCountryImages/MXN.png
    - assets/pngCountryImages/MYR.png
    - assets/pngCountryImages/MZN.png
    - assets/pngCountryImages/NAD.png
    - assets/pngCountryImages/NGN.png
    - assets/pngCountryImages/NIO.png
    - assets/pngCountryImages/NOK.png
    - assets/pngCountryImages/NPR.png
    - assets/pngCountryImages/NZD.png
    - assets/pngCountryImages/OMR.png
    - assets/pngCountryImages/PAB.png
    - assets/pngCountryImages/PEN.png
    - assets/pngCountryImages/PGK.png
    - assets/pngCountryImages/PHP.png
    - assets/pngCountryImages/PKR.png
    - assets/pngCountryImages/PLN.png
    - assets/pngCountryImages/PYG.png
    - assets/pngCountryImages/QAR.png
    - assets/pngCountryImages/RON.png
    - assets/pngCountryImages/RSD.png
    - assets/pngCountryImages/RUB.png
    - assets/pngCountryImages/RWF.png
    - assets/pngCountryImages/SAR.png
    - assets/pngCountryImages/SBD.png
    - assets/pngCountryImages/SCR.png
    - assets/pngCountryImages/SDG.png
    - assets/pngCountryImages/SEK.png
    - assets/pngCountryImages/SGD.png
    - assets/pngCountryImages/SHP.png
    - assets/pngCountryImages/SLL.png
    - assets/pngCountryImages/SOS.png
    - assets/pngCountryImages/SRD.png
    - assets/pngCountryImages/SSP.png
    - assets/pngCountryImages/STD.png
    - assets/pngCountryImages/STN.png
    - assets/pngCountryImages/SVC.png
    - assets/pngCountryImages/SYP.png
    - assets/pngCountryImages/SZL.png
    - assets/pngCountryImages/THB.png
    - assets/pngCountryImages/TJS.png
    - assets/pngCountryImages/TMT.png
    - assets/pngCountryImages/TND.png
    - assets/pngCountryImages/TOP.png
    - assets/pngCountryImages/TRY.png
    - assets/pngCountryImages/TTD.png
    - assets/pngCountryImages/TWD.png
    - assets/pngCountryImages/TZS.png
    - assets/pngCountryImages/UAH.png
    - assets/pngCountryImages/UGX.png
    - assets/pngCountryImages/USD.png
    - assets/pngCountryImages/UYU.png
    - assets/pngCountryImages/UZS.png
    - assets/pngCountryImages/VES.png
    - assets/pngCountryImages/VND.png
    - assets/pngCountryImages/VUV.png
    - assets/pngCountryImages/WST.png
    - assets/pngCountryImages/XAF.png
    - assets/pngCountryImages/XAG.png
    - assets/pngCountryImages/XAU.png
    - assets/pngCountryImages/XCD.png
    - assets/pngCountryImages/XDR.png
    - assets/pngCountryImages/XOF.png
    - assets/pngCountryImages/XPD.png
    - assets/pngCountryImages/XPF.png
    - assets/pngCountryImages/XPT.png
    - assets/pngCountryImages/YER.png
    - assets/pngCountryImages/ZAR.png
    - assets/pngCountryImages/ZMK.png
    - assets/pngCountryImages/ZMW.png
    - assets/pngCountryImages/ZWL.png
    - assets/private_key.pepk
    - assets/sample_rates.json
    - assets/supplierconfig.json
  
   

  
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
fonts:
  - asset: fonts/RobotoMono-Regular.ttf
  - asset: fonts/RobotoMono-Bold.ttf


  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
