import 'dart:ui';

class Constants {
  static const String currencyCodeFrom = "currencyCodeFrom";
  static const String currencyCodeTo = "currencyCodeTo";
  static const String themeColor="theme" ;
  static const String currencySaveData = "currencysavedata";

  static const List<Map<String,dynamic>> countryList = [

    {"code":"AED", "image":"assets/countyImage/AED.svg", "country_name":"United Arab Emirates Dirha.."},
    {"code":"AFN", "image":"assets/countyImage/AFN.svg", "country_name":"Ffghan Ffghani "},
    {"code":"ALL", "image":"assets/countyImage/ALL.svg", "country_name":"Albanian Lek"},
    {"code":"AMD", "image":"assets/countyImage/AMD.svg", "country_name":"Armenian Dram"},
    {"code":"ANG", "image":"assets/countyImage/ANG.svg", "country_name":"Netherlands Antillean Guil.."},
    {"code":"AOA", "image":"assets/countyImage/AOA.svg", "country_name":"Angolan Kwanza"},
    {"code":"ARS", "image":"assets/countyImage/ARS.svg", "country_name":"Argentine Peso"},
    {"code":"AUD", "image":"assets/countyImage/AUD.svg", "country_name":"Australian Dollar"},
    {"code":"AWG", "image":"assets/countyImage/AWG.svg", "country_name":"Aruban Florin"},
    {"code":"AZN", "image":"assets/countyImage/AZN.svg", "country_name":"AzerBaijani Manat"},
    {"code":"BAM", "image":"assets/countyImage/BAM.svg", "country_name":"Bosnia-Herzegovina Conve.."},
    {"code":"BBD", "image":"assets/countyImage/BBD.svg", "country_name":"Barbadian Dollar"},
    {"code":"BGN", "image":"assets/countyImage/BGN.svg", "country_name":"Bulgarian Lev"},
    {"code":"BHD", "image":"assets/countyImage/BHD.svg", "country_name":"Bahraini Dinar"},
    {"code":"BIF", "image":"assets/countyImage/BIF.svg", "country_name":"Burundian France"},
    {"code":"BMD", "image":"assets/countyImage/BMD.svg", "country_name":"Bermudan Dollar"},
    {"code":"BND", "image":"assets/countyImage/BND.svg", "country_name":"Brunei Dollar"},
    {"code":"BOB", "image":"assets/countyImage/BOB.svg", "country_name":"Bolivian Boliviano"},
    {"code":"BRL", "image":"assets/countyImage/BRL.svg", "country_name":"Brazilian Real"},
    {"code":"BSD", "image":"assets/countyImage/BSD.svg", "country_name":"Bahamian Dollar"},
    {"code":"BTC", "image":"assets/countyImage/BTC.svg", "country_name":"Bitcoin"},
    {"code":"BTN", "image":"assets/countyImage/BTN.svg", "country_name":"Bhutanese Ngultrum"},
    {"code":"BWP", "image":"assets/countyImage/BWP.svg", "country_name":"Botsanan Pula"},
    {"code":"BYN", "image":"assets/countyImage/BYN.svg", "country_name":"Belarusian Ruble"},
    {"code":"BZD", "image":"assets/countyImage/BZD.svg", "country_name":"Belize Dollar"},
    {"code":"CAD", "image":"assets/countyImage/CAD.svg", "country_name":"Canadian Dollar"},
    {"code":"CDF", "image":"assets/countyImage/CDF.svg", "country_name":"Congolese Franc"},
    {"code":"CHF", "image":"assets/countyImage/CHF.svg", "country_name":"Swiss Franc"},
    {"code":"CLP", "image":"assets/countyImage/CLP.svg", "country_name":"Chilean Peso"},
    {"code":"CNY", "image":"assets/countyImage/CNY.svg", "country_name":"Chinese Yuan"},
    {"code":"COP", "image":"assets/countyImage/COP.svg", "country_name":"Colombian Peso"},
    {"code":"CRC", "image":"assets/countyImage/CRC.svg", "country_name":"Costa Rican Colon"},
    {"code":"CUP", "image":"assets/countyImage/CUP.svg", "country_name":"Cuban Peso"},
    {"code":"CVE", "image":"assets/countyImage/CVE.svg", "country_name":"Cape Verdean Escudo"},
    {"code":"CZk", "image":"assets/countyImage/CZK.svg", "country_name":"Czech Republic Koruna"},
    {"code":"CLF", "image":"assets/countyImage/CLF.svg", "country_name":"Unidad de Fomento"},
    {"code":"CNH", "image":"assets/countyImage/CNH.svg", "country_name":"Renminbi"},
    {"code":"CVC", "image":"assets/countyImage/CVC.svg", "country_name":"Cabo Verde Escudoa"},
    {"code":"CUC", "image":"assets/countyImage/CUC.svg", "country_name":"Cuban Convertible Peso"},
    {"code":"DJF", "image":"assets/countyImage/DJF.svg", "country_name":"Djiboutian Franc"},
    {"code":"DKK", "image":"assets/countyImage/DKK.svg", "country_name":"Danish Krone"},
    {"code":"DOP", "image":"assets/countyImage/DOP.svg", "country_name":"Dominican Peso"},
    {"code":"DZD", "image":"assets/countyImage/DZD.svg", "country_name":"Algerian Dinar"},
    {"code":"EGP", "image":"assets/countyImage/EGP.svg", "country_name":"Egyptian Pound"},
    {"code":"ERN", "image":"assets/countyImage/ERN.svg", "country_name":"Eritrean Nakfa"},
    {"code":"ETB", "image":"assets/countyImage/ETB.svg", "country_name":"Ethiopian Birr"},
    {"code":"EUR", "image":"assets/countyImage/EUR.svg", "country_name":" Euro"},
    {"code":"FJD", "image":"assets/countyImage/FJD.svg", "country_name":"Fijian Dollar"},
    {"code":"FKP", "image":"assets/countyImage/FKP.svg", "country_name":"Falkland Islands Pound"},
    {"code":"GBP", "image":"assets/countyImage/GBP.svg", "country_name":"British Pound Sterling"},
    {"code":"GEL", "image":"assets/countyImage/GEL.svg", "country_name":" Geogian Lari "},
    {"code":"GHS", "image":"assets/countyImage/GHS.svg", "country_name":" Ghanaian Cedi "},
    {"code":"GIP", "image":"assets/countyImage/GIP.svg", "country_name":"Gibraltar Pround"},
    {"code":"GGP", "image":"assets/countyImage/GGP.svg", "country_name":"	Guernsey Pound "},
    {"code":"GMD", "image":"assets/countyImage/GMD.svg", "country_name":"Gambian Dalasi"},
    {"code":"GNF", "image":"assets/countyImage/GNF.svg", "country_name":"Guinean Franc"},
    {"code":"GTQ", "image":"assets/countyImage/GTQ.svg", "country_name":"Guatemalan Quetzal "},
    {"code":"GYD ", "image":"assets/countyImage/GYD.svg", "country_name":"Guyanaese Dollar"},
    {"code":"HKD", "image":"assets/countyImage/HKD.svg", "country_name":"Hong Kong Dollar"},
    {"code":"HNL", "image":"assets/countyImage/HNL.svg", "country_name":"Honduran Lempira"},
    {"code":"HRK ", "image":"assets/countyImage/HRK .svg","country_name":"Croatian Kuna"},
    {"code":"HTG ", "image":"assets/countyImage/HTG .svg", "country_name":"Haitian Gourda"},
    {"code":"HUF", "image":"assets/countyImage/HUF.svg", "country_name":"Hungarian Forint"},
    {"code":"IDR", "image":"assets/countyImage/IDR.svg", "country_name":"Indonesian Rupiah"},
    {"code":"ILS", "image":"assets/countyImage/ILS.svg", "country_name":"Israeli New Sheqel"},
    {"code":"INR", "image":"assets/countyImage/INR.svg", "country_name":"Indian Rupee"},
    {"code":"IQD ", "image":"assets/countyImage/IQD .svg", "country_name":"Iraqi Dinar"},
    {"code":"IRR ", "image":"assets/countyImage/IRR .svg", "country_name":"Iranian Rial"},
    {"code":"ISK", "image":"assets/countyImage/ISK.svg", "country_name":"Icelandic Krona"},
    {"code":"IMP", "image":"assets/countyImage/IMP.svg", "country_name":"	Isle of Man Pound"},
    {"code":"JMD", "image":"assets/countyImage/JMD.svg", "country_name":"Jamaican Dollar"},
    {"code":"JOD", "image":"assets/countyImage/JOD.svg", "country_name":"Jordanian Dinar"},
    {"code":"JPY", "image":"assets/countyImage/JPY.svg", "country_name":"Japanese Yen"},
    {"code":"JEP", "image":"assets/countyImage/JEP.svg", "country_name":"Jersey Pound"},
    {"code":"KES", "image":"assets/countyImage/KES.svg", "country_name":"Ke	South Korean Wonnyan Shilling"},
    {"code":"KGS", "image":"assets/countyImage/KGS.svg", "country_name":"Kyrgystani Som"},
    {"code":"KHR ", "image":"assets/countyImage/KHR.svg", "country_name":"Cambodian Rial"},
    {"code":"KMF ", "image":"assets/countyImage/KMF.svg", "country_name":"Comoraian Franc"},
    {"code":"KPW", "image":"assets/countyImage/KPW.svg", "country_name":"North Korean Won"},
    {"code":"KWD", "image":"assets/countyImage/KWD.svg", "country_name":"Kuwaiti Dinar"},
    {"code":"KYD ", "image":"assets/countyImage/KYD.svg", "country_name":"Cayman Islands Dollar"},
    {"code":"KZT", "image":"assets/countyImage/KZT.svg", "country_name":"Kazakhstani Tenge"},
    {"code":"KRW", "image":"assets/countyImage/KRW.svg", "country_name":"	South Korean Won"},
    {"code":"LAK", "image":"assets/countyImage/LAK.svg", "country_name":"Laotian Kip"},
    {"code":"LBP", "image":"assets/countyImage/LBP.svg", "country_name":"Lebanese Pound"},
    {"code":"LKR", "image":"assets/countyImage/LKR.svg", "country_name":"Shri Lankan Rupee "},
    {"code":"LRD", "image":"assets/countyImage/LRD.svg", "country_name":"Liberian Dollar"},
    {"code":"LSL", "image":"assets/countyImage/LSL.svg", "country_name":"Lesotho Loti "},
    {"code":"LYD", "image":"assets/countyImage/LYD.svg", "country_name":"Libyan Dinar"},
    {"code":"MAD ", "image":"assets/countyImage/MAD .svg", "country_name":"Moroccan Dirham "},
    {"code":"MDL ", "image":"assets/countyImage/MDL .svg", "country_name":"Moldovan Leu"},
    {"code":"MGA", "image":"assets/countyImage/MGA.svg", "country_name":"Malagasy Ariary"},
    {"code":"MKD", "image":"assets/countyImage/MKD.svg", "country_name":"Macedonian Denar"},
    {"code":"MMK", "image":"assets/countyImage/MMK.svg", "country_name":"Myanma Kyat"},
    {"code":"MNT", "image":"assets/countyImage/MNT.svg", "country_name":"Mongolian Tugrik"},
    {"code":"MOP", "image":"assets/countyImage/MOP.svg", "country_name":"Macanese Pataca"},
    {"code":"MRO", "image":"assets/countyImage/MRO.svg", "country_name":"Mauritanian Ouguiya"},
    {"code":"MUR ", "image":"assets/countyImage/MUR .svg", "country_name":"Maurtitian Rupee "},
    {"code":"MRU ", "image":"assets/countyImage/MRU .svg", "country_name":"	Mauritanian Ouguiya "},
    {"code":"MVR ", "image":"assets/countyImage/MVR .svg", "country_name":"Maldivian Rufiya"},
    {"code":"MWK ", "image":"assets/countyImage/MWK.svg", "country_name":"Malawian Kwacha"},
    {"code":"MXN", "image":"assets/countyImage/ MXN.svg", "country_name":" Mexican Peso"},
    {"code":"MYR", "image":"assets/countyImage/MYR.svg", "country_name":" Malaysian Ringgit"},
    {"code":"MZN", "image":"assets/countyImage/MZN.svg", "country_name":"Mozambican Metical"},
    {"code":"NDA", "image":"assets/countyImage/NAD.svg", "country_name":"Namibian Dollar"},
    {"code":"NGN", "image":"assets/countyImage/NGN.svg", "country_name":"Nigerian Naira"},
    {"code":"NIO", "image":"assets/countyImage/NIO.svg", "country_name":"Nicaraguan Cordoba"},
    {"code":"NOK", "image":"assets/countyImage/NOK.svg", "country_name":"Norwegian Krone"},
    {"code":"NPR", "image":"assets/countyImage/NPR.svg", "country_name":"Nepalese Rupee"},
    {"code":"NZD", "image":"assets/countyImage/NZD.svg", "country_name":"New Zealand Dollar"},
    {"code":"OMR", "image":"assets/countyImage/OMR.svg", "country_name":"Omani Rial"},
    {"code":"PAB", "image":"assets/countyImage/PAB.svg", "country_name":"Panamanian Balboa"},
    {"code":"PEN", "image":"assets/countyImage/PEN.svg", "country_name":"Peruvian Nuevo Sol"},
    {"code":"PGK", "image":"assets/countyImage/PGK.svg", "country_name":"Papua New Guinean Kina"},
    {"code":"PHP", "image":"assets/countyImage/PHP.svg", "country_name":"Philippine Rupee"},
    {"code":"PKR", "image":"assets/countyImage/PKR.svg", "country_name":"Pakistani Rupee"},
    {"code":"PLN", "image":"assets/countyImage/PLN.svg", "country_name":"Polish Zloty"},
    {"code":"PYG", "image":"assets/countyImage/PYG.svg", "country_name":"Paraguayan Guarani"},
    {"code":"QAR", "image":"assets/countyImage/QAR.svg", "country_name":"Qatari Rial"},
    {"code": "RON", "image": "assets/countyImage/RON.svg", "country_name": "Romanian leu"},
    {"code": "RSD", "image": "assets/countyImage/RSD.svg", "country_name": "Serbian Dinar"},
    {"code": "RUB", "image": "assets/countyImage/RUB.svg", "country_name": "Russian Ruble"},
    {"code": "RWF", "image": "assets/countyImage/RWF.svg", "country_name": "Rwandan Franc"},
    {"code":"SAR", "image":"assets/countyImage/SAR.svg", "country_name":"Saudi Riyal"},
    {"code":"SBD", "image":"assets/countyImage/SBD.svg", "country_name":"Salomon Islands Dollar"},
    {"code":"SCR", "image":"assets/countyImage/SCR.svg", "country_name":"Seychellois Rupee"},
    {"code": "SDG", "image": "assets/countyImage/SDG.svg", "country_name":"Sudanese Pound"},
    {"code": "SEK", "image": "assets/countyImage/SEK.svg", "country_name": "Swedish Krona "},
    {"code": "SGD", "image": "assets/countyImage/SGD.svg", "country_name": "Singapore Dollar "},
    {"code": "SHP", "image": "assets/countyImage/SHP.svg", "country_name": "Saint Helena Pound"},
    {"code": "SLL", "image": "assets/countyImage/SLL.svg", "country_name": "Sierra Leonean Leone"},
    {"code": "SOS", "image": "assets/countyImage/SOS.svg", "country_name": "Somali Shilling"},
    {"code": "SRD", "image": "assets/countyImage/SRD.svg", "country_name": "Surinamese Dollar"},
    {"code": "SSP", "image": "assets/countyImage/SSP.svg", "country_name": "South Sudanese Pound"},
    {"code": "STD", "image": "assets/countyImage/STD.svg", "country_name": "São Tomé and Príncipe"},
    {"code": "SYP", "image": "assets/countyImage/SYP.svg", "country_name": "Syrian Pound "},
    {"code": "SZL", "image": "assets/countyImage/SZL.svg", "country_name": "Swazi Lilangebi"},
    {"code": "STN", "image": "assets/countyImage/STN.svg", "country_name": "El Salvador Colon"},
    {"code": "SBC", "image": "assets/countyImage/SBC.svg", "country_name": "El Salvador Colon"},
    {"code": "THB", "image": "assets/countyImage/THB.svg", "country_name": "Thai Baht"},
    {"code": "TJS", "image": "assets/countyImage/TJS.svg", "country_name": "Tajikistani Somoni"},
    {"code": "TMT", "image": "assets/countyImage/TMT.svg", "country_name": "Turkmenistani Manat "},
    {"code": "TND", "image": "assets/countyImage/TND.svg", "country_name": "Tunisian Dinar "},
    {"code": "TOP", "image": "assets/countyImage/TOP.svg", "country_name": "Tongan Pa'anga "},
    {"code": "TRY", "image": "assets/countyImage/TRY.svg", "country_name": "Turkish Lira"},
    {"code": "TTD", "image": "assets/countyImage/TTD.svg", "country_name": "Trinidad and Tobago Dollar"},
    {"code": "TWD", "image": "assets/countyImage/TWD.svg", "country_name": "New Taiwan Dollar"},
    {"code": "TZS", "image": "assets/countyImage/TZS.svg", "country_name": "Tanzanian Shilling"},
    {"code": "UAH", "image": "assets/countyImage/UAH.svg", "country_name": "Ukrainian Hryvnia "},
    {"code": "UGX", "image": "assets/countyImage/UGX.svg", "country_name": "Ugandan Shilling"},
    {"code": "USD", "image": "assets/countyImage/USD.svg", "country_name": "United States Dollar"},
    {"code": "UYU", "image": "assets/countyImage/UYU.svg","country_name": "Uruguayan Peso"},
    {"code": "UZS", "image": "assets/countyImage/UZS.svg", "country_name": "Uzbekistan Som "},
    {"code": "VES", "image": "assets/countyImage/VES.svg", "country_name": "Venezuelan Bolivar Fuerte "},
    {"code": "VND", "image": "assets/countyImage/VND.svg", "country_name": "Vietnamese Dong "},
    {"code": "VUV", "image": "assets/countyImage/VUV.svg", "country_name": "Vanuatu Vatu "},
    {"code": "WST", "image": "assets/countyImage/WST.svg", "country_name": "Samoan Tala "},
    {"code": "XAF", "image": "assets/countyImage/XAF.svg", "country_name": "CFA Franc BEAC "},
    {"code": "XCD", "image": "assets/countyImage/XCD.svg", "country_name": "East Caribbean Dollar "},
    {"code": "XOF", "image": "assets/countyImage/XOF.svg", "country_name": "CFA Franc BCEAO "},
    {"code": "XAG", "image": "assets/countyImage/XAG.svg", "country_name": "Swazi Lilangebi"},
    {"code": "XAU", "image": "assets/countyImage/XAU.svg", "country_name": "Vietnam Dong"},
    {"code": "XDR", "image": "assets/countyImage/XDR.svg", "country_name": "Special Drawing Rights"},
    {"code": "XPD", "image": "assets/countyImage/XPD.svg", "country_name": "Ounce of palladium"},
    {"code": "XPT", "image": "assets/countyImage/XPT.svg", "country_name": "Ounce of platinum"},
    {"code": "XPF", "image": "assets/countyImage/XPF.svg", "country_name": "CFP Franc"},
    {"code": "YER", "image": "assets/countyImage/YER.svg", "country_name": "Yemeni Rial"},
    {"code": "ZAR", "image": "assets/countyImage/ZAR.svg", "country_name": "south African Rand"},
    {"code": "ZWL", "image": "assets/countyImage/ZWL.svg", "country_name": "Zimbabwean dollar"},
    {"code": "ZMW", "image": "assets/countyImage/ZMV.svg", "country_name": "Zambia"},
  ];



}
